// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCawsQ8kXzVhUcFZOo4injOaearlWwBXsQ',
    appId: '1:835946728382:web:76ba5d7528c3977323c7ef',
    messagingSenderId: '835946728382',
    projectId: 'skillradar-b854d',
    authDomain: 'skillradar-b854d.firebaseapp.com',
    storageBucket: 'skillradar-b854d.appspot.com',
    measurementId: 'G-Q00K4WK41Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6SMLQ7pa0AYXIwJnfVgtZ3mSvJeFNh2U',
    appId: '1:835946728382:android:d91a166b6ff0980d23c7ef',
    messagingSenderId: '835946728382',
    projectId: 'skillradar-b854d',
    storageBucket: 'skillradar-b854d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMlZVXKDFW6UkNpnzpAgCkBWTmoJNeugw',
    appId: '1:835946728382:ios:208edcaae1231be323c7ef',
    messagingSenderId: '835946728382',
    projectId: 'skillradar-b854d',
    storageBucket: 'skillradar-b854d.appspot.com',
    androidClientId: '835946728382-iidgdmmuh4m692f30e14gv6a5hba04h4.apps.googleusercontent.com',
    iosClientId: '835946728382-fqtljkjp8g4tipfosb6mvns4oau7jp86.apps.googleusercontent.com',
    iosBundleId: 'com.skillradar.skillradar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMlZVXKDFW6UkNpnzpAgCkBWTmoJNeugw',
    appId: '1:835946728382:ios:b99c751795a80b0623c7ef',
    messagingSenderId: '835946728382',
    projectId: 'skillradar-b854d',
    storageBucket: 'skillradar-b854d.appspot.com',
    androidClientId: '835946728382-iidgdmmuh4m692f30e14gv6a5hba04h4.apps.googleusercontent.com',
    iosClientId: '835946728382-9ef41dhdrr91bg8j94h4jaio65fh6264.apps.googleusercontent.com',
    iosBundleId: 'com.example.fundzApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCawsQ8kXzVhUcFZOo4injOaearlWwBXsQ',
    appId: '1:835946728382:web:a784c88df53656d223c7ef',
    messagingSenderId: '835946728382',
    projectId: 'skillradar-b854d',
    authDomain: 'skillradar-b854d.firebaseapp.com',
    storageBucket: 'skillradar-b854d.appspot.com',
    measurementId: 'G-BV3BYXYKTH',
  );
}
