List<String> skillList = [
  'Flutter developer',
  'Forex Trader',
  'Web3 Developer',
  'Anime Otaku',
  'Cybersecurity Engineer',
  'Marine Engineer',
  'Content Creator',
  'Engineer',
  'Software Developer',
  'Teacher',
  'Doctor',
  'Nurse',
  'Lawyer',
  'Accountant',
  'Manager',
  'Graphic Designer',
  'Web Developer',
  'Data Scientist',
  'Researcher',
  'Writer',
  'Journalist',
  'Photographer',
  'Architect',
  'Pharmacist',
  'Pilot',
  'Chef',
  'Mechanic',
  'Construction Worker',
  'Real Estate Agent',
  'Entrepreneur',
  'Barber',
  'Tailor',
  'Plumber',
  'Electrician',
  'Carpenter',
  'Welder',
  'Baker',
  'Bartender',
  'Massage Therapist',
  'Personal Trainer',
  'Florist',
  'Event Planner',
  'Interpreter',
  'Librarian',
  'Social Worker',
  'Fitness Trainer',
  'Martial Arts Instructor',
  'Dance Instructor',
  'Driver',
  'Marketer',
  'Salesperson',
  'Customer Service Representative',
  'IT Specialist',
  'Security Guard',
  'Police Officer',
  'Firefighter',
  'Soldier',
  'Dentist',
  'Optometrist',
  'Veterinarian',
  'Psychologist',
  'Counselor',
  'Therapist',
  'Real Estate Appraiser',
  'Surveyor',
  'Urban Planner',
  'Civil Servant',
  'Politician',
  'Actor',
  'Musician',
  'Artist',
  'Sculptor',
  'Director',
  'Producer',
  'Editor',
  'Sound Engineer',
  'Lighting Designer',
  'Set Designer',
  'Costume Designer',
  'Makeup Artist',
  'Choreographer',
  'Broadcaster',
  'Television Host',
  'Radio Host',
  'Voice Actor',
  'Model',
  'Comedian',
  'Public Relations Specialist',
  'Human Resources Specialist',
  'Training and Development Specialist',
  'Operations Manager',
  'Supply Chain Manager',
  'Logistics Coordinator',
  'Procurement Specialist',
  'Quality Control Inspector',
  'Manufacturing Worker',
  'Assembly Line Worker',
  'Warehouse Manager',
  'Shipping and Receiving Clerk',
  'Environmental Scientist',
  'Conservationist',
  'Farmer',
  'Forester',
  'Fisherman',
  'Miner',
  'Oil and Gas Worker',
  'Renewable Energy Technician',
  'Aerospace Engineer',
  'Astronomer',
  'Geologist',
  'Meteorologist',
  'Oceanographer',
  'Zoologist',
  'Botanist',
  'Ecologist',
  'Geneticist',
  'Microbiologist',
  'Pathologist',
  'Immunologist',
  'Dermatologist',
  'Endocrinologist',
  'Gastroenterologist',
  'Hematologist',
  'Nephrologist',
  'Oncologist',
  'Pediatrician',
  'Radiologist',
  'Urologist',
  'Anesthesiologist',
  'Surgeon',
  'Orthopedic Surgeon',
  'Ophthalmologist',
  'Obstetrician/Gynecologist',
  'Podiatrist',
  'Public Health Specialist',
];
